import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

async function main() {
  console.log("Seeding database...");

  await prisma.activityLog.deleteMany();
  await prisma.chatMessage.deleteMany();
  await prisma.review.deleteMany();
  await prisma.favorite.deleteMany();
  await prisma.inquiry.deleteMany();
  await prisma.property.deleteMany();
  await prisma.user.deleteMany();

  const hashedAdmin = await bcrypt.hash("admin123", 12);
  const hashedUser = await bcrypt.hash("user123", 12);

  const admin = await prisma.user.create({
    data: {
      name: "Admin",
      email: "admin@propertypointers.com",
      password: hashedAdmin,
      phone: "+91-9876543210",
      role: "admin",
      verified: true,
      city: "Noida",
      state: "Uttar Pradesh",
    },
  });

  const users = await Promise.all([
    prisma.user.create({
      data: {
        name: "Rahul Sharma",
        email: "user@propertypointers.com",
        password: hashedUser,
        phone: "+91-9876543211",
        role: "user",
        verified: true,
        city: "Noida",
        state: "Uttar Pradesh",
        latitude: 28.5355,
        longitude: 77.391,
      },
    }),
    prisma.user.create({
      data: {
        name: "Priya Patel",
        email: "priya@propertypointers.com",
        password: hashedUser,
        phone: "+91-9876543212",
        role: "owner",
        verified: true,
        city: "Mumbai",
        state: "Maharashtra",
        latitude: 19.076,
        longitude: 72.8777,
      },
    }),
    prisma.user.create({
      data: {
        name: "Amit Kumar",
        email: "amit@propertypointers.com",
        password: hashedUser,
        phone: "+91-9876543213",
        role: "agent",
        verified: true,
        city: "Delhi",
        state: "Delhi",
        latitude: 28.6139,
        longitude: 77.209,
      },
    }),
    prisma.user.create({
      data: {
        name: "Sneha Gupta",
        email: "sneha@propertypointers.com",
        password: hashedUser,
        phone: "+91-9876543214",
        role: "owner",
        verified: false,
        city: "Gurgaon",
        state: "Haryana",
      },
    }),
    prisma.user.create({
      data: {
        name: "Vikram Singh",
        email: "vikram@propertypointers.com",
        password: hashedUser,
        phone: "+91-9876543215",
        role: "user",
        city: "Bangalore",
        state: "Karnataka",
      },
    }),
  ]);

  const propertyImages = {
    apartment: [
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop",
    ],
    house: [
      "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
    ],
    villa: [
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&h=600&fit=crop",
    ],
    commercial: [
      "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=600&fit=crop",
    ],
    plot: [
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&h=600&fit=crop",
    ],
  };

  const properties = [
    {
      title: "Luxury 3BHK Apartment in Sector 150, Noida",
      description: "Spacious 3BHK apartment with modern amenities in one of Noida's prime locations. This premium apartment features large balconies with panoramic views, modular kitchen, and 24/7 security. Located near Noida Expressway with excellent connectivity to Delhi NCR. The society offers world-class amenities including swimming pool, gym, club house, and landscaped gardens.",
      price: 9500000,
      type: "sale",
      category: "apartment",
      bedrooms: 3,
      bathrooms: 2,
      balconies: 2,
      area: 1450,
      floor: "12",
      totalFloors: "24",
      facing: "East",
      furnishing: "semi-furnished",
      age: "1-3 years",
      address: "Gaur City 2, Sector 150",
      locality: "Sector 150",
      city: "Noida",
      state: "Uttar Pradesh",
      pincode: "201310",
      latitude: 28.5677,
      longitude: 77.4223,
      images: JSON.stringify(propertyImages.apartment),
      amenities: JSON.stringify(["Parking", "Lift", "Security", "Power Backup", "Swimming Pool", "Gym", "Club House", "Garden", "Children Play Area", "CCTV"]),
      verified: true,
      featured: true,
      ownerId: users[1].id,
      ownerType: "owner",
      views: 342,
    },
    {
      title: "Modern 2BHK Flat for Rent in Indirapuram",
      description: "Well-maintained 2BHK flat available for rent in Indirapuram, Ghaziabad. Fully furnished with AC, modular kitchen, and premium fittings. Walking distance to metro station and shopping malls. Ideal for families and working professionals. 24/7 water supply and power backup available.",
      price: 18000,
      type: "rent",
      category: "apartment",
      bedrooms: 2,
      bathrooms: 2,
      balconies: 1,
      area: 1100,
      floor: "5",
      totalFloors: "12",
      facing: "North",
      furnishing: "furnished",
      age: "3-5 years",
      address: "Ahinsa Khand 2, Indirapuram",
      locality: "Indirapuram",
      city: "Ghaziabad",
      state: "Uttar Pradesh",
      pincode: "201014",
      latitude: 28.6352,
      longitude: 77.3577,
      images: JSON.stringify([propertyImages.apartment[1], propertyImages.apartment[2]]),
      amenities: JSON.stringify(["Parking", "Lift", "Security", "Power Backup", "Gym", "CCTV", "Air Conditioning", "Wi-Fi"]),
      verified: true,
      featured: true,
      ownerId: users[0].id,
      ownerType: "owner",
      views: 189,
    },
    {
      title: "Premium Villa in DLF Phase 5, Gurgaon",
      description: "Exquisite 5BHK independent villa in DLF Phase 5. Spread across 5000 sqft with private garden, modern interiors, and smart home features. This villa offers unparalleled luxury with Italian marble flooring, designer bathroom fittings, and a private swimming pool. Perfect for families seeking premium living.",
      price: 85000000,
      type: "sale",
      category: "villa",
      bedrooms: 5,
      bathrooms: 5,
      balconies: 3,
      area: 5000,
      facing: "South",
      furnishing: "furnished",
      age: "0-1 years",
      address: "DLF Phase 5",
      locality: "DLF Phase 5",
      city: "Gurgaon",
      state: "Haryana",
      pincode: "122002",
      latitude: 28.4595,
      longitude: 77.0913,
      images: JSON.stringify(propertyImages.villa),
      amenities: JSON.stringify(["Parking", "Security", "Power Backup", "Swimming Pool", "Garden", "CCTV", "Fire Safety", "Intercom", "Solar Panels", "EV Charging"]),
      verified: true,
      featured: true,
      premium: true,
      ownerId: users[2].id,
      ownerType: "agent",
      views: 567,
    },
    {
      title: "Commercial Office Space in Connaught Place, Delhi",
      description: "Prime commercial office space available in the heart of Delhi at Connaught Place. Ideal for corporate offices, startups, and co-working spaces. Fully air-conditioned with modular workstations, conference room, and pantry. Excellent connectivity via metro and road networks.",
      price: 250000,
      type: "rent",
      category: "office",
      area: 2500,
      floor: "3",
      totalFloors: "8",
      facing: "North-East",
      furnishing: "furnished",
      age: "5-10 years",
      address: "Block A, Connaught Place",
      locality: "Connaught Place",
      city: "Delhi",
      state: "Delhi",
      pincode: "110001",
      latitude: 28.6315,
      longitude: 77.2167,
      images: JSON.stringify(propertyImages.commercial),
      amenities: JSON.stringify(["Parking", "Lift", "Security", "Power Backup", "CCTV", "Fire Safety", "Air Conditioning", "Wi-Fi", "Intercom"]),
      verified: true,
      featured: true,
      ownerId: users[2].id,
      ownerType: "agent",
      views: 234,
    },
    {
      title: "Residential Plot in Greater Noida West",
      description: "200 sq yard residential plot available in a gated community in Greater Noida West. Clear title, RERA registered, with all approvals in place. Well-connected to Noida-Greater Noida Expressway. Ideal for building your dream home with excellent appreciation potential.",
      price: 3500000,
      type: "sale",
      category: "plot",
      area: 1800,
      facing: "East",
      address: "Sector 1, Greater Noida West",
      locality: "Greater Noida West",
      city: "Greater Noida",
      state: "Uttar Pradesh",
      pincode: "201308",
      latitude: 28.4729,
      longitude: 77.5009,
      images: JSON.stringify(propertyImages.plot),
      amenities: JSON.stringify(["Security", "Garden", "Children Play Area", "Jogging Track", "Rain Water Harvesting"]),
      verified: true,
      featured: false,
      ownerId: users[3].id,
      ownerType: "owner",
      views: 145,
    },
    {
      title: "4BHK Penthouse in Powai, Mumbai",
      description: "Stunning 4BHK penthouse with breathtaking lake view in Powai, Mumbai. Duplex layout with private terrace garden, home theater, and designer interiors. Premium location near IT hubs and international schools. A rare find for luxury living in Mumbai's prestigious neighborhood.",
      price: 120000000,
      type: "sale",
      category: "apartment",
      bedrooms: 4,
      bathrooms: 4,
      balconies: 3,
      area: 3800,
      floor: "22",
      totalFloors: "22",
      facing: "West",
      furnishing: "furnished",
      age: "0-1 years",
      address: "Hiranandani Gardens, Powai",
      locality: "Powai",
      city: "Mumbai",
      state: "Maharashtra",
      pincode: "400076",
      latitude: 19.1197,
      longitude: 72.9051,
      images: JSON.stringify([propertyImages.apartment[0], propertyImages.villa[0], propertyImages.villa[1]]),
      amenities: JSON.stringify(["Parking", "Lift", "Security", "Power Backup", "Swimming Pool", "Gym", "Club House", "Garden", "CCTV", "Fire Safety", "Intercom", "Waste Management"]),
      verified: true,
      featured: true,
      premium: true,
      ownerId: users[1].id,
      ownerType: "owner",
      views: 891,
    },
    {
      title: "3BHK Independent House in Whitefield, Bangalore",
      description: "Spacious 3BHK independent house in Whitefield with garden and car parking. Well-connected to IT corridors and ITPL. This property features a large living room, modular kitchen, and vastu-compliant design. Peaceful residential neighborhood with good schools and hospitals nearby.",
      price: 15000000,
      type: "sale",
      category: "house",
      bedrooms: 3,
      bathrooms: 3,
      balconies: 1,
      area: 2200,
      facing: "North",
      furnishing: "semi-furnished",
      age: "3-5 years",
      address: "Whitefield Main Road",
      locality: "Whitefield",
      city: "Bangalore",
      state: "Karnataka",
      pincode: "560066",
      latitude: 12.9698,
      longitude: 77.7499,
      images: JSON.stringify(propertyImages.house),
      amenities: JSON.stringify(["Parking", "Security", "Power Backup", "Garden", "CCTV", "Rain Water Harvesting", "Solar Panels"]),
      verified: true,
      featured: false,
      ownerId: users[2].id,
      ownerType: "agent",
      views: 276,
    },
    {
      title: "Retail Shop in Saket, New Delhi",
      description: "Prime location retail shop in Select Citywalk Mall area, Saket. Ground floor shop with excellent footfall and visibility. Ideal for branded retail, food & beverage, or lifestyle stores. Surrounded by premium malls and residential areas.",
      price: 35000000,
      type: "sale",
      category: "shop",
      area: 800,
      floor: "Ground",
      facing: "South",
      furnishing: "unfurnished",
      age: "5-10 years",
      address: "Saket District Centre",
      locality: "Saket",
      city: "Delhi",
      state: "Delhi",
      pincode: "110017",
      latitude: 28.5238,
      longitude: 77.2090,
      images: JSON.stringify(propertyImages.commercial),
      amenities: JSON.stringify(["Parking", "Security", "Power Backup", "CCTV", "Fire Safety", "Lift"]),
      verified: false,
      featured: false,
      ownerId: users[3].id,
      ownerType: "owner",
      views: 112,
    },
    {
      title: "1BHK Studio Apartment for Rent in Koramangala",
      description: "Cozy 1BHK fully furnished studio apartment in Koramangala, Bangalore. Perfect for working professionals. Walking distance to restaurants, cafes, and offices. Modern interiors with washing machine, refrigerator, and microwave included.",
      price: 22000,
      type: "rent",
      category: "apartment",
      bedrooms: 1,
      bathrooms: 1,
      area: 550,
      floor: "3",
      totalFloors: "6",
      facing: "East",
      furnishing: "furnished",
      age: "1-3 years",
      address: "5th Block, Koramangala",
      locality: "Koramangala",
      city: "Bangalore",
      state: "Karnataka",
      pincode: "560095",
      latitude: 12.9352,
      longitude: 77.6245,
      images: JSON.stringify([propertyImages.apartment[1]]),
      amenities: JSON.stringify(["Security", "Power Backup", "Lift", "CCTV", "Air Conditioning", "Wi-Fi"]),
      verified: true,
      featured: true,
      ownerId: users[0].id,
      ownerType: "owner",
      views: 423,
    },
    {
      title: "2BHK Apartment in Baner, Pune",
      description: "New 2BHK apartment in Baner, one of Pune's fastest-growing neighborhoods. Premium society with modern amenities. Close to IT parks, malls, and the Mumbai-Pune Expressway. Ideal for young families and professionals.",
      price: 6500000,
      type: "sale",
      category: "apartment",
      bedrooms: 2,
      bathrooms: 2,
      balconies: 1,
      area: 950,
      floor: "7",
      totalFloors: "15",
      facing: "West",
      furnishing: "semi-furnished",
      age: "Under Construction",
      address: "Baner Road",
      locality: "Baner",
      city: "Pune",
      state: "Maharashtra",
      pincode: "411045",
      latitude: 18.5596,
      longitude: 73.7858,
      images: JSON.stringify([propertyImages.apartment[2], propertyImages.apartment[0]]),
      amenities: JSON.stringify(["Parking", "Lift", "Security", "Power Backup", "Swimming Pool", "Gym", "Garden", "Children Play Area"]),
      verified: true,
      featured: false,
      ownerId: users[1].id,
      ownerType: "owner",
      views: 198,
    },
    {
      title: "3BHK Flat in Gachibowli, Hyderabad",
      description: "Modern 3BHK flat near Financial District, Gachibowli. Close to top IT companies, international schools, and hospitals. Well-ventilated apartments with premium finishes and club-class amenities.",
      price: 8500000,
      type: "sale",
      category: "apartment",
      bedrooms: 3,
      bathrooms: 2,
      balconies: 2,
      area: 1350,
      floor: "9",
      totalFloors: "18",
      facing: "North-East",
      furnishing: "unfurnished",
      age: "0-1 years",
      address: "Nanakramguda Road, Gachibowli",
      locality: "Gachibowli",
      city: "Hyderabad",
      state: "Telangana",
      pincode: "500032",
      latitude: 17.4401,
      longitude: 78.3489,
      images: JSON.stringify([propertyImages.apartment[0], propertyImages.apartment[2]]),
      amenities: JSON.stringify(["Parking", "Lift", "Security", "Power Backup", "Swimming Pool", "Gym", "Club House", "CCTV", "Jogging Track", "EV Charging"]),
      verified: true,
      featured: true,
      ownerId: users[2].id,
      ownerType: "agent",
      views: 315,
    },
    {
      title: "Farmhouse with Land in Chattarpur, Delhi",
      description: "Beautiful farmhouse with 2 acres of land in Chattarpur, South Delhi. Lush green surroundings, private entrance, and peaceful environment. Perfect for weekend getaways or permanent residence away from city noise.",
      price: 200000000,
      type: "sale",
      category: "house",
      bedrooms: 4,
      bathrooms: 4,
      area: 8000,
      facing: "South",
      furnishing: "furnished",
      age: "5-10 years",
      address: "Chattarpur Enclave",
      locality: "Chattarpur",
      city: "Delhi",
      state: "Delhi",
      pincode: "110074",
      latitude: 28.5025,
      longitude: 77.1709,
      images: JSON.stringify([propertyImages.villa[2], propertyImages.house[0], propertyImages.house[1]]),
      amenities: JSON.stringify(["Parking", "Security", "Power Backup", "Swimming Pool", "Garden", "CCTV", "Solar Panels"]),
      verified: true,
      featured: false,
      premium: true,
      ownerId: users[3].id,
      ownerType: "owner",
      views: 654,
    },
  ];

  for (const prop of properties) {
    await prisma.property.create({ data: prop as any });
  }

  await prisma.siteSettings.upsert({
    where: { id: "default" },
    create: {},
    update: {},
  });

  console.log(`Seeded: ${users.length + 1} users, ${properties.length} properties`);
  console.log("\nLogin credentials:");
  console.log("Admin: admin@propertypointers.com / admin123");
  console.log("User:  user@propertypointers.com / user123");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
