import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const DEMO_PROJECTS = [
  {
    title: "Devika Vibe Sector 110",
    slug: "devika-vibe-sector-110",
    description:
      "Step into VIBE – The Premium Hub in Sector 110, Noida. Spread across 75,000 sq. ft., it's a dynamic blend of luxury retail, vibrant dining, and immersive experiences. Every moment here is crafted to captivate. Located near premium residential societies with high footfall area.",
    highlights: JSON.stringify([
      "Possession Soon",
      "Catchment Area of 50K+ Families",
      "Engaging Kids Play Area",
      "State-of-the-Art Infrastructure & Design",
      "Seamless Connectivity to Expressways",
      "Low Maintenance Charges",
      "Prime Location in Noida Sector 110",
      "Grand Entrance with 4 Entry & Exit Points",
    ]),
    builderName: "Devika Group",
    location: "Sector 110, Noida",
    city: "Noida",
    state: "Uttar Pradesh",
    reraNumber: "UPRERAPRJ9275",
    projectStatus: "under-construction",
    possessionDate: "December 2025",
    startingPrice: 60,
    priceUnit: "Lac",
    propertyType: "commercial",
    configurations: JSON.stringify(["Retail Shops", "Food Court", "Kiosks"]),
    totalArea: "1.25 Acres",
    totalUnits: 280,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800",
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800",
      "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800",
    ]),
    amenities: JSON.stringify([
      "Power Backup", "Lift", "Security", "Visitor Parking", "Gymnasium",
      "Rain Water Harvesting", "Air Conditioned", "Earthquake Resistant",
      "Kids Play Area", "Fire Fighting Equipment", "CCTV Surveillance",
      "Cafeteria", "Grand Entrance Lobby", "Event Space",
    ]),
    locationAdvantages: JSON.stringify([
      { place: "Yamuna Expressway", distance: "15 min" },
      { place: "Mahamaya Flyover", distance: "5 min" },
      { place: "Metro Station", distance: "7 min" },
      { place: "Noida-Greater Noida Expressway", distance: "1 min" },
      { place: "Yatharth Hospital", distance: "2 min" },
      { place: "Akshardham Temple", distance: "15 min" },
    ]),
    floorPlans: JSON.stringify([]),
    featured: true,
    verified: true,
  },
  {
    title: "M3M The Cullinan Sector 94",
    slug: "m3m-the-cullinan-sector-94",
    description:
      "M3M The Cullinan is an ultra-luxury residential and commercial project in Sector 94, Noida. Offering 3, 4, and 5 BHK apartments with world-class amenities, it redefines luxury living with panoramic views of the F1 track and golf course. A lifestyle curated for the elite.",
    highlights: JSON.stringify([
      "Ultra-Luxury 3/4/5 BHK Apartments",
      "Panoramic F1 Track & Golf Course Views",
      "World-Class Club with Infinity Pool",
      "Smart Home Automation in Every Unit",
      "Italian Marble Flooring Throughout",
      "Premium Modular Kitchen by European Brand",
    ]),
    builderName: "M3M Group",
    location: "Sector 94, Noida",
    city: "Noida",
    state: "Uttar Pradesh",
    reraNumber: "UPRERAPRJ442214",
    projectStatus: "under-construction",
    possessionDate: "April 2028",
    startingPrice: 4.5,
    priceUnit: "Cr",
    propertyType: "mixed",
    configurations: JSON.stringify(["3 BHK", "4 BHK", "5 BHK", "Penthouse", "Commercial"]),
    totalArea: "12 Acres",
    totalUnits: 400,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800",
    ]),
    amenities: JSON.stringify([
      "Swimming Pool", "Gymnasium", "Club House", "Spa & Sauna", "Tennis Court",
      "Jogging Track", "Kids Play Area", "24/7 Security", "Power Backup",
      "Landscaped Gardens", "EV Charging Stations", "Concierge Service",
      "Private Theater", "Business Center", "Rooftop Lounge",
    ]),
    locationAdvantages: JSON.stringify([
      { place: "F1 Buddh International Circuit", distance: "10 min" },
      { place: "Noida Expressway", distance: "5 min" },
      { place: "DND Flyway", distance: "15 min" },
      { place: "Sector 18 Market", distance: "12 min" },
      { place: "Fortis Hospital", distance: "8 min" },
    ]),
    floorPlans: JSON.stringify([]),
    featured: true,
    verified: true,
  },
  {
    title: "DLF The Arbour Sector 63",
    slug: "dlf-the-arbour-sector-63",
    description:
      "DLF The Arbour offers ultra-luxury 4 BHK apartments in Sector 63, Gurgaon. Spread across 25 acres of lush greens with low density living. Designed by world-renowned architects, it's a masterpiece of modern luxury with private lobbies and dedicated concierge.",
    highlights: JSON.stringify([
      "Low Density - Only 280 Apartments",
      "25 Acres of Lush Green Landscape",
      "Private Lobby for Each Tower",
      "Designed by Hafeez Contractor",
      "Triple-height Grand Entrance",
      "Dedicated Golf Cart Service",
    ]),
    builderName: "DLF Limited",
    location: "Sector 63, Gurgaon",
    city: "Gurgaon",
    state: "Haryana",
    reraNumber: "RC/HARERA/GGM/2023/101",
    projectStatus: "under-construction",
    possessionDate: "March 2027",
    startingPrice: 7,
    priceUnit: "Cr",
    propertyType: "residential",
    configurations: JSON.stringify(["4 BHK", "4.5 BHK", "Penthouse"]),
    totalArea: "25 Acres",
    totalUnits: 280,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800",
      "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800",
    ]),
    amenities: JSON.stringify([
      "Swimming Pool", "Gymnasium", "Club House", "Tennis Court", "Squash Court",
      "Mini Theater", "Yoga Room", "Indoor Games", "Jogging Track",
      "24/7 CCTV Surveillance", "Power Backup", "Earthquake Resistant",
    ]),
    locationAdvantages: JSON.stringify([
      { place: "Golf Course Road", distance: "5 min" },
      { place: "Rapid Metro Station", distance: "10 min" },
      { place: "Cyber City", distance: "12 min" },
      { place: "IGI Airport", distance: "25 min" },
      { place: "Medanta Hospital", distance: "15 min" },
    ]),
    floorPlans: JSON.stringify([]),
    featured: true,
    verified: true,
  },
  {
    title: "Godrej Tropical Isle Sector 146",
    slug: "godrej-tropical-isle-sector-146",
    description:
      "Godrej Tropical Isle brings a resort-style living experience to Sector 146, Noida. Inspired by tropical architecture, it offers 2, 3, and 4 BHK apartments surrounded by water features and tropical landscaping. Experience luxury that feels like a permanent vacation.",
    highlights: JSON.stringify([
      "Tropical Resort-Style Architecture",
      "3-Side Open Apartments",
      "Water Features & Lagoon Pool",
      "Tropical Landscaping by International Firm",
      "Double-Height Entrance Lobbies",
    ]),
    builderName: "Godrej Properties",
    location: "Sector 146, Noida",
    city: "Noida",
    state: "Uttar Pradesh",
    reraNumber: "UPRERAPRJ585234",
    projectStatus: "under-construction",
    possessionDate: "June 2028",
    startingPrice: 2.5,
    priceUnit: "Cr",
    propertyType: "residential",
    configurations: JSON.stringify(["2 BHK", "3 BHK", "4 BHK"]),
    totalArea: "10 Acres",
    totalUnits: 500,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800",
      "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=800",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800",
    ]),
    amenities: JSON.stringify([
      "Lagoon Pool", "Gymnasium", "Club House", "Tropical Gardens",
      "Meditation Zone", "Kids Play Area", "Amphitheater",
      "24/7 Security", "EV Charging", "Jogging Track",
    ]),
    locationAdvantages: JSON.stringify([
      { place: "FNG Expressway", distance: "3 min" },
      { place: "Noida Expressway", distance: "5 min" },
      { place: "Botanical Garden Metro", distance: "15 min" },
      { place: "Fortis Hospital", distance: "10 min" },
    ]),
    floorPlans: JSON.stringify([]),
    featured: false,
    verified: true,
  },
  {
    title: "Paras Avenue Sector 129",
    slug: "paras-avenue-sector-129",
    description:
      "Paras Avenue is a premium commercial project in Sector 129, Noida offering high-street retail, food court, and entertainment spaces. Located on the Noida Expressway with direct visibility and excellent connectivity, it's a prime investment opportunity.",
    highlights: JSON.stringify([
      "High-Street Retail on Noida Expressway",
      "Direct Expressway Visibility & Frontage",
      "3-Side Open Commercial Complex",
      "Premium Food Court & Entertainment Zone",
      "Ample Parking for 500+ Vehicles",
    ]),
    builderName: "Paras Buildtech",
    location: "Sector 129, Noida",
    city: "Noida",
    state: "Uttar Pradesh",
    reraNumber: "UPRERAPRJ297873",
    projectStatus: "under-construction",
    possessionDate: "September 2027",
    startingPrice: 55,
    priceUnit: "Lac",
    propertyType: "commercial",
    configurations: JSON.stringify(["Retail Shops", "Food Court", "Anchor Stores"]),
    totalArea: "3 Acres",
    totalUnits: 350,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800",
      "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800",
      "https://images.unsplash.com/photo-1554469384-e58fac16e23a?w=800",
    ]),
    amenities: JSON.stringify([
      "Power Backup", "Lift", "Escalators", "Security",
      "Visitor Parking", "Fire Safety", "Rainwater Harvesting",
      "Central AC", "Loading/Unloading Bay",
    ]),
    locationAdvantages: JSON.stringify([
      { place: "Noida Expressway", distance: "On Expressway" },
      { place: "Sector 137 Metro", distance: "5 min" },
      { place: "Jaypee Hospital", distance: "7 min" },
      { place: "Greater Noida Expressway", distance: "10 min" },
    ]),
    floorPlans: JSON.stringify([]),
    featured: false,
    verified: true,
  },
  {
    title: "Prestige Lakeside Habitat",
    slug: "prestige-lakeside-habitat",
    description:
      "Prestige Lakeside Habitat is a sprawling 80-acre township in Whitefield, Bangalore offering 1-4 BHK apartments and villas. With a 5-acre central lake, it offers an unparalleled living experience with world-class facilities and lush greenery.",
    highlights: JSON.stringify([
      "80-Acre Integrated Township",
      "5-Acre Natural Lake at Center",
      "Ready-to-Move Apartments & Villas",
      "Multiple Schools & Shopping Within Township",
      "International-Standard Sports Complex",
    ]),
    builderName: "Prestige Group",
    location: "Whitefield, Bangalore",
    city: "Bangalore",
    state: "Karnataka",
    reraNumber: "PRM/KA/RERA/2020/003",
    projectStatus: "ready-to-move",
    possessionDate: "Ready to Move",
    startingPrice: 85,
    priceUnit: "Lac",
    propertyType: "residential",
    configurations: JSON.stringify(["1 BHK", "2 BHK", "3 BHK", "4 BHK", "Villa"]),
    totalArea: "80 Acres",
    totalUnits: 3000,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800",
      "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800",
      "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800",
      "https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=800",
    ]),
    amenities: JSON.stringify([
      "Swimming Pool", "Gymnasium", "Club House", "Lake View Jogging Track",
      "Tennis Court", "Basketball Court", "Badminton Court", "Cricket Net",
      "Yoga Room", "Kids Play Area", "Amphitheater", "Party Hall",
      "24/7 Security", "Power Backup", "Rainwater Harvesting",
    ]),
    locationAdvantages: JSON.stringify([
      { place: "Whitefield Railway Station", distance: "5 min" },
      { place: "ITPL Tech Park", distance: "10 min" },
      { place: "Bangalore Airport", distance: "40 min" },
      { place: "Forum Mall", distance: "8 min" },
      { place: "Columbia Asia Hospital", distance: "7 min" },
    ]),
    floorPlans: JSON.stringify([]),
    featured: true,
    verified: true,
  },
  {
    title: "Smartworld Elie Saab Noida",
    slug: "smartworld-elie-saab-noida",
    description:
      "A collaboration between Smartworld Developers and global fashion icon Elie Saab, this ultra-luxury project in Sector 98, Noida brings haute couture design to residential living. Every detail reflects elegance, from designer lobbies to bespoke interiors.",
    highlights: JSON.stringify([
      "Designed by Fashion Icon Elie Saab",
      "Bespoke Interiors with Designer Touch",
      "Exclusive Residents-Only Lounge",
      "Rooftop Infinity Pool with City Views",
      "Dedicated Valet & Concierge Service",
    ]),
    builderName: "Smartworld Developers",
    location: "Sector 98, Noida",
    city: "Noida",
    state: "Uttar Pradesh",
    reraNumber: "UPRERAPRJ300532",
    projectStatus: "upcoming",
    possessionDate: "October 2030",
    startingPrice: 6,
    priceUnit: "Cr",
    propertyType: "residential",
    configurations: JSON.stringify(["3 BHK", "4 BHK", "5 BHK", "Penthouse"]),
    totalArea: "15 Acres",
    totalUnits: 350,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800",
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800",
    ]),
    amenities: JSON.stringify([
      "Infinity Pool", "Private Gym", "Spa", "Designer Club",
      "Concierge Service", "Private Theater", "Wine Cellar",
      "Rooftop Garden", "Art Gallery", "Helipad",
    ]),
    locationAdvantages: JSON.stringify([
      { place: "Noida Expressway", distance: "2 min" },
      { place: "DND Flyway", distance: "15 min" },
      { place: "Sector 18 Market", distance: "10 min" },
      { place: "Max Hospital", distance: "5 min" },
    ]),
    floorPlans: JSON.stringify([]),
    featured: true,
    verified: true,
  },
  {
    title: "Lodha The Park Worli",
    slug: "lodha-the-park-worli",
    description:
      "Lodha The Park redefines luxury living in Mumbai's most prestigious address - Worli. With stunning sea views, world-class amenities by Trump Organization, and bespoke interiors, this is where Mumbai's elite choose to live. Featuring the tallest residential towers in Worli.",
    highlights: JSON.stringify([
      "Sea-Facing Luxury Apartments in Worli",
      "Amenities Curated by Trump Organization",
      "Private Elevator for Each Apartment",
      "Bespoke Interiors by Armani/Casa",
      "270-Degree Panoramic Sea Views",
    ]),
    builderName: "Lodha Group",
    location: "Worli, Mumbai",
    city: "Mumbai",
    state: "Maharashtra",
    reraNumber: "P51800001234",
    projectStatus: "ready-to-move",
    possessionDate: "Ready to Move",
    startingPrice: 8,
    priceUnit: "Cr",
    propertyType: "residential",
    configurations: JSON.stringify(["3 BHK", "4 BHK", "5 BHK", "Duplex Penthouse"]),
    totalArea: "17 Acres",
    totalUnits: 600,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800",
    ]),
    amenities: JSON.stringify([
      "Infinity Pool", "Private Beach Club", "Spa & Wellness Center",
      "Golf Simulator", "Squash Court", "Tennis Court",
      "Private Dining Room", "Residents Lounge", "Kids Zone",
      "Business Center", "24/7 Concierge", "Valet Parking",
    ]),
    locationAdvantages: JSON.stringify([
      { place: "Bandra Worli Sea Link", distance: "5 min" },
      { place: "Bandra Kurla Complex", distance: "10 min" },
      { place: "Mumbai Airport", distance: "25 min" },
      { place: "Lilavati Hospital", distance: "8 min" },
    ]),
    floorPlans: JSON.stringify([]),
    featured: true,
    verified: true,
  },
  {
    title: "BPTP Amstoria Plots Sector 102",
    slug: "bptp-amstoria-plots-sector-102",
    description:
      "BPTP Amstoria offers premium residential plots in Sector 102, Gurgaon on Dwarka Expressway. Build your dream home on RERA-approved plots with world-class infrastructure, gated community, and excellent connectivity to Delhi and IGI Airport.",
    highlights: JSON.stringify([
      "Gated Community with 24/7 Security",
      "Plots on Dwarka Expressway",
      "Well-Planned Infrastructure & Roads",
      "Community Parks & Green Belts",
      "Close to Diplomatic Enclave",
    ]),
    builderName: "BPTP Limited",
    location: "Sector 102, Gurgaon",
    city: "Gurgaon",
    state: "Haryana",
    reraNumber: "RC/HARERA/GGM/2022/78",
    projectStatus: "ready-to-move",
    possessionDate: "Ready to Move",
    startingPrice: 2,
    priceUnit: "Cr",
    propertyType: "plots",
    configurations: JSON.stringify(["200 Sq Yd", "300 Sq Yd", "500 Sq Yd", "1000 Sq Yd"]),
    totalArea: "200 Acres",
    totalUnits: 1200,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800",
      "https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800",
    ]),
    amenities: JSON.stringify([
      "Gated Community", "Wide Internal Roads", "Underground Electricity",
      "Sewage Treatment Plant", "Community Center", "Parks & Jogging Track",
      "24/7 Security", "CCTV Surveillance",
    ]),
    locationAdvantages: JSON.stringify([
      { place: "Dwarka Expressway", distance: "On Expressway" },
      { place: "IGI Airport", distance: "20 min" },
      { place: "Diplomatic Enclave", distance: "10 min" },
      { place: "Cyber Hub", distance: "15 min" },
    ]),
    floorPlans: JSON.stringify([]),
    featured: false,
    verified: true,
  },
  {
    title: "Max Estate 128 Noida",
    slug: "max-estate-128-noida",
    description:
      "Max Estate brings premium office spaces to Sector 128, Noida Expressway. Grade A+ commercial towers with LEED Gold certification, smart building management, and modern co-working spaces. Perfect for MNCs and growing startups looking for premium office address.",
    highlights: JSON.stringify([
      "Grade A+ Commercial Office Space",
      "LEED Gold Certified Green Building",
      "Smart Building Management System",
      "Premium Co-working Spaces Available",
      "Dedicated Bus Shuttle Service",
    ]),
    builderName: "Max Estates",
    location: "Sector 128, Noida",
    city: "Noida",
    state: "Uttar Pradesh",
    reraNumber: "UPRERAPRJ671234",
    projectStatus: "under-construction",
    possessionDate: "December 2026",
    startingPrice: 1.2,
    priceUnit: "Cr",
    propertyType: "commercial",
    configurations: JSON.stringify(["Office Suites", "Co-working Space", "Retail"]),
    totalArea: "8 Acres",
    totalUnits: 200,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800",
      "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800",
      "https://images.unsplash.com/photo-1554469384-e58fac16e23a?w=800",
    ]),
    amenities: JSON.stringify([
      "Central AC", "High-Speed Elevators", "Underground Parking",
      "Food Court", "Conference Rooms", "Business Lounge",
      "Power Backup", "Fire Safety", "CCTV", "EV Charging",
    ]),
    locationAdvantages: JSON.stringify([
      { place: "Noida Expressway", distance: "On Expressway" },
      { place: "Sector 137 Metro", distance: "8 min" },
      { place: "Greater Noida Expressway", distance: "15 min" },
      { place: "Jaypee Hospital", distance: "10 min" },
    ]),
    floorPlans: JSON.stringify([]),
    featured: false,
    verified: true,
  },
];

async function main() {
  console.log("Seeding projects...");

  await prisma.project.deleteMany();
  console.log("Cleared existing projects.");

  for (const project of DEMO_PROJECTS) {
    await prisma.project.create({ data: project });
    console.log(`  Created: ${project.title}`);
  }

  console.log(`\nSeeded ${DEMO_PROJECTS.length} demo projects.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
