import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

async function main() {
  console.log("=== Full Database Seed (MongoDB) ===\n");

  console.log("Clearing existing data...");
  await prisma.activityLog.deleteMany();
  await prisma.chatMessage.deleteMany();
  await prisma.review.deleteMany();
  await prisma.favorite.deleteMany();
  await prisma.inquiry.deleteMany();
  await prisma.blogPost.deleteMany();
  await prisma.property.deleteMany();
  await prisma.project.deleteMany();
  await prisma.user.deleteMany();
  console.log("  Done.\n");

  // ===================== USERS =====================
  console.log("Seeding users...");
  const hashedAdmin = await bcrypt.hash("admin123", 12);
  const hashedUser = await bcrypt.hash("user123", 12);

  const admin = await prisma.user.create({
    data: {
      name: "Admin",
      email: "admin@propertypointers.com",
      password: hashedAdmin,
      phone: "+91-9876543210",
      role: "admin",
      verified: true,
      city: "Noida",
      state: "Uttar Pradesh",
    },
  });

  const users = await Promise.all([
    prisma.user.create({ data: { name: "Rahul Sharma", email: "user@propertypointers.com", password: hashedUser, phone: "+91-9876543211", role: "user", verified: true, city: "Noida", state: "Uttar Pradesh" } }),
    prisma.user.create({ data: { name: "Priya Patel", email: "priya@propertypointers.com", password: hashedUser, phone: "+91-9876543212", role: "owner", verified: true, city: "Mumbai", state: "Maharashtra" } }),
    prisma.user.create({ data: { name: "Amit Kumar", email: "amit@propertypointers.com", password: hashedUser, phone: "+91-9876543213", role: "agent", verified: true, city: "Delhi", state: "Delhi" } }),
    prisma.user.create({ data: { name: "Sneha Gupta", email: "sneha@propertypointers.com", password: hashedUser, phone: "+91-9876543214", role: "owner", verified: false, city: "Gurgaon", state: "Haryana" } }),
    prisma.user.create({ data: { name: "Vikram Singh", email: "vikram@propertypointers.com", password: hashedUser, phone: "+91-9876543215", role: "user", city: "Bangalore", state: "Karnataka" } }),
    prisma.user.create({ data: { name: "Deepak Verma", email: "deepak@propertypointers.com", password: hashedUser, phone: "+91-9876543216", role: "agent", verified: true, city: "Noida", state: "Uttar Pradesh" } }),
    prisma.user.create({ data: { name: "Meera Reddy", email: "meera@propertypointers.com", password: hashedUser, phone: "+91-9876543217", role: "owner", verified: true, city: "Hyderabad", state: "Telangana" } }),
  ]);
  console.log(`  Created ${users.length + 1} users.\n`);

  // ===================== PROPERTIES =====================
  console.log("Seeding properties...");
  const img = {
    apt: ["https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop"],
    house: ["https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop"],
    villa: ["https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&h=600&fit=crop"],
    comm: ["https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800&h=600&fit=crop"],
    plot: ["https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1625244724120-1fd1d34d00f6?w=800&h=600&fit=crop"],
    shop: ["https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=800&h=600&fit=crop"],
    pg: ["https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop"],
  };
  const o = (i: number) => users[i % users.length].id;

  const properties: any[] = [
    { title: "Luxury 3BHK Apartment in Sector 150, Noida", description: "Spacious 3BHK apartment with modern amenities in one of Noida's prime locations.", price: 9500000, type: "sale", category: "apartment", bedrooms: 3, bathrooms: 2, balconies: 2, area: 1450, floor: "12", totalFloors: "24", facing: "East", furnishing: "semi-furnished", age: "1-3 years", address: "Gaur City 2, Sector 150", locality: "Sector 150", city: "Noida", state: "Uttar Pradesh", pincode: "201310", images: JSON.stringify(img.apt), amenities: JSON.stringify(["Parking", "Lift", "Security", "Power Backup", "Swimming Pool", "Gym", "Club House"]), verified: true, featured: true, ownerId: o(1), ownerType: "owner", views: 342 },
    { title: "4BHK Penthouse in Powai, Mumbai", description: "Stunning 4BHK penthouse with breathtaking lake view in Powai.", price: 120000000, type: "sale", category: "apartment", bedrooms: 4, bathrooms: 4, balconies: 3, area: 3800, floor: "22", totalFloors: "22", facing: "West", furnishing: "furnished", age: "0-1 years", address: "Hiranandani Gardens, Powai", locality: "Powai", city: "Mumbai", state: "Maharashtra", pincode: "400076", images: JSON.stringify([img.apt[0], img.villa[0]]), amenities: JSON.stringify(["Parking", "Lift", "Security", "Power Backup", "Swimming Pool", "Gym"]), verified: true, featured: true, premium: true, ownerId: o(1), ownerType: "owner", views: 891 },
    { title: "2BHK Apartment in Baner, Pune", description: "New 2BHK apartment in Baner with modern amenities.", price: 6500000, type: "sale", category: "apartment", bedrooms: 2, bathrooms: 2, balconies: 1, area: 950, floor: "7", totalFloors: "15", facing: "West", furnishing: "semi-furnished", age: "Under Construction", address: "Baner Road", locality: "Baner", city: "Pune", state: "Maharashtra", pincode: "411045", images: JSON.stringify([img.apt[2], img.apt[0]]), amenities: JSON.stringify(["Parking", "Lift", "Security", "Swimming Pool", "Gym"]), verified: true, ownerId: o(1), ownerType: "owner", views: 198 },
    { title: "3BHK Flat in Gachibowli, Hyderabad", description: "Modern 3BHK flat near Financial District.", price: 8500000, type: "sale", category: "apartment", bedrooms: 3, bathrooms: 2, balconies: 2, area: 1350, floor: "9", totalFloors: "18", facing: "North-East", furnishing: "unfurnished", age: "0-1 years", address: "Nanakramguda Road", locality: "Gachibowli", city: "Hyderabad", state: "Telangana", pincode: "500032", images: JSON.stringify([img.apt[0], img.apt[2]]), amenities: JSON.stringify(["Parking", "Lift", "Security", "Gym", "Jogging Track"]), verified: true, featured: true, ownerId: o(2), ownerType: "agent", views: 315 },
    { title: "2BHK Premium Apartment in Whitefield, Bangalore", description: "Brand new 2BHK apartment near ITPL.", price: 7200000, type: "sale", category: "apartment", bedrooms: 2, bathrooms: 2, balconies: 1, area: 1100, floor: "14", totalFloors: "20", facing: "South-East", furnishing: "unfurnished", age: "0-1 years", address: "ITPL Main Road", locality: "Whitefield", city: "Bangalore", state: "Karnataka", pincode: "560066", images: JSON.stringify([img.apt[1], img.apt[2]]), amenities: JSON.stringify(["Parking", "Lift", "Security", "Swimming Pool", "Gym"]), verified: true, featured: true, ownerId: o(4), ownerType: "owner", views: 256 },
    { title: "Modern 2BHK for Rent in Indirapuram", description: "Fully furnished 2BHK flat near metro.", price: 18000, type: "rent", category: "apartment", bedrooms: 2, bathrooms: 2, balconies: 1, area: 1100, floor: "5", totalFloors: "12", facing: "North", furnishing: "furnished", age: "3-5 years", address: "Ahinsa Khand 2", locality: "Indirapuram", city: "Ghaziabad", state: "Uttar Pradesh", pincode: "201014", images: JSON.stringify([img.apt[1], img.apt[2]]), amenities: JSON.stringify(["Parking", "Lift", "Security", "Gym", "Wi-Fi"]), verified: true, featured: true, ownerId: o(0), ownerType: "owner", views: 189 },
    { title: "1BHK Studio in Koramangala, Bangalore", description: "Fully furnished studio apartment for professionals.", price: 22000, type: "rent", category: "apartment", bedrooms: 1, bathrooms: 1, area: 550, floor: "3", totalFloors: "6", facing: "East", furnishing: "furnished", age: "1-3 years", address: "5th Block, Koramangala", locality: "Koramangala", city: "Bangalore", state: "Karnataka", pincode: "560095", images: JSON.stringify([img.apt[1]]), amenities: JSON.stringify(["Security", "Power Backup", "Lift", "Wi-Fi"]), verified: true, featured: true, ownerId: o(0), ownerType: "owner", views: 423 },
    { title: "3BHK Furnished Flat in Andheri West, Mumbai", description: "Beautifully furnished 3BHK near DN Nagar metro.", price: 65000, type: "rent", category: "apartment", bedrooms: 3, bathrooms: 2, balconies: 2, area: 1400, floor: "16", totalFloors: "22", facing: "West", furnishing: "furnished", age: "3-5 years", address: "Lokhandwala Complex", locality: "Andheri West", city: "Mumbai", state: "Maharashtra", pincode: "400053", images: JSON.stringify(img.apt), amenities: JSON.stringify(["Parking", "Lift", "Security", "Swimming Pool"]), verified: true, ownerId: o(1), ownerType: "owner", views: 287 },
    { title: "2BHK Apartment for Rent in Sector 62, Noida", description: "Semi-furnished 2BHK near metro station.", price: 15000, type: "rent", category: "apartment", bedrooms: 2, bathrooms: 2, balconies: 1, area: 1000, floor: "4", totalFloors: "10", facing: "North-East", furnishing: "semi-furnished", age: "5-10 years", address: "Block A, Sector 62", locality: "Sector 62", city: "Noida", state: "Uttar Pradesh", pincode: "201301", images: JSON.stringify([img.apt[2]]), amenities: JSON.stringify(["Parking", "Lift", "Security"]), verified: true, ownerId: o(5), ownerType: "agent", views: 145 },
    { title: "3BHK Independent House in Whitefield", description: "Spacious independent house with garden.", price: 15000000, type: "sale", category: "house", bedrooms: 3, bathrooms: 3, balconies: 1, area: 2200, facing: "North", furnishing: "semi-furnished", age: "3-5 years", address: "Whitefield Main Road", locality: "Whitefield", city: "Bangalore", state: "Karnataka", pincode: "560066", images: JSON.stringify(img.house), amenities: JSON.stringify(["Parking", "Security", "Power Backup", "Garden"]), verified: true, ownerId: o(2), ownerType: "agent", views: 276 },
    { title: "4BHK Builder Floor in Greater Kailash, Delhi", description: "Newly built 4BHK in GK-1 with modern architecture.", price: 45000000, type: "sale", category: "house", bedrooms: 4, bathrooms: 4, balconies: 2, area: 2800, floor: "2", totalFloors: "4", facing: "East", furnishing: "semi-furnished", age: "0-1 years", address: "M Block, Greater Kailash 1", locality: "Greater Kailash", city: "Delhi", state: "Delhi", pincode: "110048", images: JSON.stringify(img.house), amenities: JSON.stringify(["Parking", "Security", "Power Backup", "Lift"]), verified: true, featured: true, premium: true, ownerId: o(2), ownerType: "agent", views: 487 },
    { title: "3BHK Builder Floor in Sector 57, Gurgaon", description: "Premium ground floor with private garden.", price: 18000000, type: "sale", category: "house", bedrooms: 3, bathrooms: 3, balconies: 1, area: 1800, floor: "Ground", totalFloors: "3", facing: "South", furnishing: "unfurnished", age: "1-3 years", address: "Sector 57", locality: "Sector 57", city: "Gurgaon", state: "Haryana", pincode: "122011", images: JSON.stringify([img.house[0], img.house[2]]), amenities: JSON.stringify(["Parking", "Security", "Garden"]), verified: true, ownerId: o(3), ownerType: "owner", views: 198 },
    { title: "Premium Villa in DLF Phase 5, Gurgaon", description: "5BHK independent villa with smart home features.", price: 85000000, type: "sale", category: "villa", bedrooms: 5, bathrooms: 5, balconies: 3, area: 5000, facing: "South", furnishing: "furnished", age: "0-1 years", address: "DLF Phase 5", locality: "DLF Phase 5", city: "Gurgaon", state: "Haryana", pincode: "122002", images: JSON.stringify(img.villa), amenities: JSON.stringify(["Parking", "Security", "Swimming Pool", "Garden", "EV Charging"]), verified: true, featured: true, premium: true, ownerId: o(2), ownerType: "agent", views: 567 },
    { title: "4BHK Luxury Villa in Jubilee Hills, Hyderabad", description: "Contemporary villa with rooftop infinity pool.", price: 65000000, type: "sale", category: "villa", bedrooms: 4, bathrooms: 4, balconies: 2, area: 4200, facing: "East", furnishing: "furnished", age: "1-3 years", address: "Road No. 36, Jubilee Hills", locality: "Jubilee Hills", city: "Hyderabad", state: "Telangana", pincode: "500033", images: JSON.stringify(img.villa), amenities: JSON.stringify(["Parking", "Security", "Swimming Pool", "Home Theater", "Gym"]), verified: true, featured: true, premium: true, ownerId: o(6), ownerType: "owner", views: 723 },
    { title: "3BHK Villa in Sarjapur Road, Bangalore", description: "Gated community villa with vastu-compliant design.", price: 25000000, type: "sale", category: "villa", bedrooms: 3, bathrooms: 3, balconies: 2, area: 2800, facing: "North-East", furnishing: "semi-furnished", age: "0-1 years", address: "Rainbow Drive Layout", locality: "Sarjapur Road", city: "Bangalore", state: "Karnataka", pincode: "560035", images: JSON.stringify([img.villa[2], img.villa[0]]), amenities: JSON.stringify(["Parking", "Security", "Swimming Pool", "Club House"]), verified: true, ownerId: o(4), ownerType: "owner", views: 389 },
    { title: "Residential Plot in Greater Noida West", description: "200 sq yard plot in gated community.", price: 3500000, type: "sale", category: "plot", area: 1800, facing: "East", address: "Sector 1, Greater Noida West", locality: "Greater Noida West", city: "Greater Noida", state: "Uttar Pradesh", pincode: "201308", images: JSON.stringify(img.plot), amenities: JSON.stringify(["Security", "Garden"]), verified: true, ownerId: o(3), ownerType: "owner", views: 145 },
    { title: "Corner Plot in Sector 92, Gurgaon", description: "Premium corner plot near Dwarka Expressway.", price: 12000000, type: "sale", category: "plot", area: 2700, facing: "North-East", address: "Sector 92", locality: "Sector 92", city: "Gurgaon", state: "Haryana", pincode: "122505", images: JSON.stringify(img.plot), amenities: JSON.stringify(["Security", "Boundary Wall"]), verified: true, featured: true, ownerId: o(3), ownerType: "owner", views: 234 },
    { title: "Commercial Office in Connaught Place, Delhi", description: "Prime office space in the heart of Delhi.", price: 250000, type: "rent", category: "office", area: 2500, floor: "3", totalFloors: "8", facing: "North-East", furnishing: "furnished", age: "5-10 years", address: "Block A, Connaught Place", locality: "Connaught Place", city: "Delhi", state: "Delhi", pincode: "110001", images: JSON.stringify(img.comm), amenities: JSON.stringify(["Parking", "Lift", "Security", "AC", "Wi-Fi"]), verified: true, featured: true, ownerId: o(2), ownerType: "agent", views: 234 },
    { title: "IT Office in Sector 62, Noida", description: "Plug-and-play office with 50 workstations.", price: 120000, type: "rent", category: "office", area: 3000, floor: "6", totalFloors: "12", facing: "North", furnishing: "furnished", age: "1-3 years", address: "A Block, Sector 62", locality: "Sector 62", city: "Noida", state: "Uttar Pradesh", pincode: "201301", images: JSON.stringify([img.comm[1]]), amenities: JSON.stringify(["Parking", "Lift", "Security", "Cafeteria"]), verified: true, ownerId: o(5), ownerType: "agent", views: 167 },
    { title: "Premium Office in BKC, Mumbai", description: "Grade-A office with panoramic city views.", price: 500000, type: "rent", category: "office", area: 5000, floor: "15", totalFloors: "25", facing: "West", furnishing: "furnished", age: "0-1 years", address: "One BKC", locality: "BKC", city: "Mumbai", state: "Maharashtra", pincode: "400051", images: JSON.stringify(img.comm), amenities: JSON.stringify(["Parking", "Lift", "Security", "Central AC", "Gym"]), verified: true, featured: true, premium: true, ownerId: o(1), ownerType: "owner", views: 456 },
    { title: "Retail Shop in Saket, New Delhi", description: "Prime shop near Select Citywalk Mall.", price: 35000000, type: "sale", category: "shop", area: 800, floor: "Ground", facing: "South", furnishing: "unfurnished", age: "5-10 years", address: "Saket District Centre", locality: "Saket", city: "Delhi", state: "Delhi", pincode: "110017", images: JSON.stringify(img.shop), amenities: JSON.stringify(["Parking", "Security", "CCTV"]), ownerId: o(3), ownerType: "owner", views: 112 },
    { title: "Showroom on MG Road, Bangalore", description: "Double-height showroom with premium glass facade.", price: 45000000, type: "sale", category: "shop", area: 1500, floor: "Ground", totalFloors: "2", facing: "North", furnishing: "unfurnished", age: "5-10 years", address: "MG Road", locality: "MG Road", city: "Bangalore", state: "Karnataka", pincode: "560001", images: JSON.stringify([img.comm[0], img.shop[0]]), amenities: JSON.stringify(["Parking", "Security", "Central AC"]), verified: true, featured: true, ownerId: o(4), ownerType: "owner", views: 267 },
    { title: "Boys PG in Sector 62, Noida", description: "Furnished PG with meals and Wi-Fi for professionals.", price: 8000, type: "pg", category: "apartment", bedrooms: 1, bathrooms: 1, area: 150, floor: "2", totalFloors: "3", facing: "North", furnishing: "furnished", age: "1-3 years", address: "Block J, Sector 62", locality: "Sector 62", city: "Noida", state: "Uttar Pradesh", pincode: "201301", images: JSON.stringify(img.pg), amenities: JSON.stringify(["Wi-Fi", "Meals", "Housekeeping", "Laundry"]), verified: true, ownerId: o(0), ownerType: "owner", views: 567 },
    { title: "Girls PG in Koramangala, Bangalore", description: "Safe PG for women with home-cooked meals.", price: 12000, type: "pg", category: "apartment", bedrooms: 1, bathrooms: 1, area: 180, floor: "1", totalFloors: "3", facing: "East", furnishing: "furnished", age: "3-5 years", address: "4th Block, Koramangala", locality: "Koramangala", city: "Bangalore", state: "Karnataka", pincode: "560034", images: JSON.stringify(img.pg), amenities: JSON.stringify(["Wi-Fi", "Meals", "Housekeeping", "Security"]), verified: true, featured: true, ownerId: o(4), ownerType: "owner", views: 432 },
  ];

  for (const prop of properties) {
    await prisma.property.create({ data: prop });
  }
  console.log(`  Created ${properties.length} properties.\n`);

  // ===================== BLOG POST =====================
  console.log("Seeding blog post...");
  await prisma.blogPost.create({
    data: {
      title: "How to Check if a Project is RERA Approved Before Buying a Property",
      slug: "how-to-check-rera-approved-project-before-buying",
      excerpt: "Buying a home is one of the biggest financial decisions. Learn how to verify RERA registration and protect yourself from fraud.",
      content: `Buying a home is one of the biggest financial decisions for most people. To protect homebuyers from fraud, delays, and misleading promises, the Government of India introduced the Real Estate (Regulation and Development) Act, 2016, commonly known as RERA.\n\nRERA was created to bring transparency, accountability, and trust to the real estate sector. Today, every residential or commercial project above a certain size must be registered with the respective state's RERA authority.\n\n## What is a RERA Approved Project?\n\nA RERA-approved project is one that has been officially registered with the state's Real Estate Regulatory Authority.\n\nTo obtain RERA registration, developers must submit key project details such as:\n- Project layout and approvals\n- Construction timeline\n- Land ownership documents\n- Financial disclosures\n\n## Why Checking RERA Approval is Important\n\n### 1. Protection Against Project Delays\nBuilders registered under RERA must follow the committed project timeline.\n\n### 2. Transparency in Project Details\nDevelopers must disclose all important project information.\n\n### 3. Financial Accountability\nRERA requires builders to deposit 70% of project funds in an escrow account.\n\n### 4. Legal Protection for Buyers\nBuyers can file complaints directly with the RERA authority.\n\n## How to Check if a Project is RERA Approved\n\n### Step 1: Visit the State RERA Website\nEach state has its own RERA portal.\n\n### Step 2: Go to the Project Registration Section\nLook for "Registered Projects" or "Project Search".\n\n### Step 3: Enter Project or Builder Details\nSearch using project name, builder name, or RERA number.\n\n### Step 4: Verify Project Details\nReview the RERA registration number, timeline, and approvals.\n\n## Conclusion\nBefore buying any property, verifying RERA approval is crucial. Property platforms like Property Pointers list verified projects to help homebuyers make informed decisions.`,
      coverImage: "/blog/rera-check-project.png",
      category: "legal",
      tags: JSON.stringify(["RERA", "property buying", "real estate law", "home buyer guide"]),
      published: true,
      views: 0,
      authorId: admin.id,
    },
  });
  console.log("  Created 1 blog post.\n");

  // ===================== PROJECTS =====================
  console.log("Seeding projects...");
  const projects = [
    { title: "Devika Vibe Sector 110", slug: "devika-vibe-sector-110", description: "Premium Hub in Sector 110, Noida. 75,000 sq. ft. of luxury retail, vibrant dining, and immersive experiences.", highlights: JSON.stringify(["Possession Soon", "50K+ Families Catchment", "State-of-the-Art Design", "Seamless Connectivity", "Low Maintenance", "4 Entry & Exit Points"]), builderName: "Devika Group", location: "Sector 110, Noida", city: "Noida", state: "Uttar Pradesh", reraNumber: "UPRERAPRJ9275", projectStatus: "under-construction", possessionDate: "December 2025", startingPrice: 60, priceUnit: "Lac", propertyType: "commercial", configurations: JSON.stringify(["Retail Shops", "Food Court", "Kiosks"]), totalArea: "1.25 Acres", totalUnits: 280, images: JSON.stringify(["https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800", "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800", "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800"]), amenities: JSON.stringify(["Power Backup", "Lift", "Security", "Visitor Parking", "Gymnasium", "Rain Water Harvesting", "Air Conditioned", "Kids Play Area", "Fire Fighting", "CCTV", "Cafeteria", "Grand Lobby"]), locationAdvantages: JSON.stringify([{ place: "Yamuna Expressway", distance: "15 min" }, { place: "Metro Station", distance: "7 min" }, { place: "Yatharth Hospital", distance: "2 min" }]), floorPlans: JSON.stringify([]), featured: true, verified: true },
    { title: "M3M The Cullinan Sector 94", slug: "m3m-the-cullinan-sector-94", description: "Ultra-luxury residential and commercial project with panoramic views of F1 track and golf course.", highlights: JSON.stringify(["3/4/5 BHK Apartments", "F1 Track & Golf Views", "Infinity Pool", "Smart Home Automation", "Italian Marble Flooring"]), builderName: "M3M Group", location: "Sector 94, Noida", city: "Noida", state: "Uttar Pradesh", reraNumber: "UPRERAPRJ442214", projectStatus: "under-construction", possessionDate: "April 2028", startingPrice: 4.5, priceUnit: "Cr", propertyType: "mixed", configurations: JSON.stringify(["3 BHK", "4 BHK", "5 BHK", "Penthouse"]), totalArea: "12 Acres", totalUnits: 400, images: JSON.stringify(["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800", "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800", "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800"]), amenities: JSON.stringify(["Swimming Pool", "Gymnasium", "Club House", "Spa", "Tennis Court", "Jogging Track", "Kids Play Area", "24/7 Security", "EV Charging", "Concierge Service"]), locationAdvantages: JSON.stringify([{ place: "F1 Circuit", distance: "10 min" }, { place: "Noida Expressway", distance: "5 min" }, { place: "DND Flyway", distance: "15 min" }]), floorPlans: JSON.stringify([]), featured: true, verified: true },
    { title: "DLF The Arbour Sector 63", slug: "dlf-the-arbour-sector-63", description: "Ultra-luxury 4 BHK apartments across 25 acres of lush greens with low density living.", highlights: JSON.stringify(["Only 280 Apartments", "25 Acres Landscape", "Private Lobbies", "Designed by Hafeez Contractor", "Golf Cart Service"]), builderName: "DLF Limited", location: "Sector 63, Gurgaon", city: "Gurgaon", state: "Haryana", reraNumber: "RC/HARERA/GGM/2023/101", projectStatus: "under-construction", possessionDate: "March 2027", startingPrice: 7, priceUnit: "Cr", propertyType: "residential", configurations: JSON.stringify(["4 BHK", "4.5 BHK", "Penthouse"]), totalArea: "25 Acres", totalUnits: 280, images: JSON.stringify(["https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800", "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800", "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800"]), amenities: JSON.stringify(["Swimming Pool", "Gymnasium", "Club House", "Tennis Court", "Squash Court", "Mini Theater", "Yoga Room", "Jogging Track"]), locationAdvantages: JSON.stringify([{ place: "Golf Course Road", distance: "5 min" }, { place: "Rapid Metro", distance: "10 min" }, { place: "Cyber City", distance: "12 min" }, { place: "IGI Airport", distance: "25 min" }]), floorPlans: JSON.stringify([]), featured: true, verified: true },
    { title: "Godrej Tropical Isle Sector 146", slug: "godrej-tropical-isle-sector-146", description: "Resort-style living with tropical architecture, water features, and lagoon pool.", highlights: JSON.stringify(["Tropical Architecture", "3-Side Open Apartments", "Lagoon Pool", "International Landscaping"]), builderName: "Godrej Properties", location: "Sector 146, Noida", city: "Noida", state: "Uttar Pradesh", reraNumber: "UPRERAPRJ585234", projectStatus: "under-construction", possessionDate: "June 2028", startingPrice: 2.5, priceUnit: "Cr", propertyType: "residential", configurations: JSON.stringify(["2 BHK", "3 BHK", "4 BHK"]), totalArea: "10 Acres", totalUnits: 500, images: JSON.stringify(["https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800", "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=800"]), amenities: JSON.stringify(["Lagoon Pool", "Gymnasium", "Club House", "Tropical Gardens", "Kids Play Area", "Amphitheater", "24/7 Security"]), locationAdvantages: JSON.stringify([{ place: "FNG Expressway", distance: "3 min" }, { place: "Noida Expressway", distance: "5 min" }]), floorPlans: JSON.stringify([]), featured: false, verified: true },
    { title: "Paras Avenue Sector 129", slug: "paras-avenue-sector-129", description: "Premium commercial project on Noida Expressway with direct visibility and excellent connectivity.", highlights: JSON.stringify(["High-Street Retail", "Direct Expressway Visibility", "500+ Vehicle Parking", "Entertainment Zone"]), builderName: "Paras Buildtech", location: "Sector 129, Noida", city: "Noida", state: "Uttar Pradesh", reraNumber: "UPRERAPRJ297873", projectStatus: "under-construction", possessionDate: "September 2027", startingPrice: 55, priceUnit: "Lac", propertyType: "commercial", configurations: JSON.stringify(["Retail Shops", "Food Court", "Anchor Stores"]), totalArea: "3 Acres", totalUnits: 350, images: JSON.stringify(["https://images.unsplash.com/photo-1497366216548-37526070297c?w=800", "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800"]), amenities: JSON.stringify(["Power Backup", "Lift", "Escalators", "Security", "Fire Safety", "Central AC"]), locationAdvantages: JSON.stringify([{ place: "Noida Expressway", distance: "On Expressway" }, { place: "Sector 137 Metro", distance: "5 min" }]), floorPlans: JSON.stringify([]), featured: false, verified: true },
    { title: "Prestige Lakeside Habitat", slug: "prestige-lakeside-habitat", description: "80-acre township with 5-acre central lake, apartments, and villas in Whitefield, Bangalore.", highlights: JSON.stringify(["80-Acre Township", "5-Acre Natural Lake", "Ready to Move", "Schools & Shopping Within"]), builderName: "Prestige Group", location: "Whitefield, Bangalore", city: "Bangalore", state: "Karnataka", reraNumber: "PRM/KA/RERA/2020/003", projectStatus: "ready-to-move", possessionDate: "Ready to Move", startingPrice: 85, priceUnit: "Lac", propertyType: "residential", configurations: JSON.stringify(["1 BHK", "2 BHK", "3 BHK", "4 BHK", "Villa"]), totalArea: "80 Acres", totalUnits: 3000, images: JSON.stringify(["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800", "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800", "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800"]), amenities: JSON.stringify(["Swimming Pool", "Gymnasium", "Club House", "Tennis Court", "Basketball Court", "Jogging Track", "Kids Play Area", "24/7 Security"]), locationAdvantages: JSON.stringify([{ place: "ITPL Tech Park", distance: "10 min" }, { place: "Bangalore Airport", distance: "40 min" }]), floorPlans: JSON.stringify([]), featured: true, verified: true },
    { title: "Smartworld Elie Saab Noida", slug: "smartworld-elie-saab-noida", description: "Ultra-luxury project by fashion icon Elie Saab with bespoke interiors.", highlights: JSON.stringify(["Designed by Elie Saab", "Bespoke Interiors", "Rooftop Infinity Pool", "Valet & Concierge"]), builderName: "Smartworld Developers", location: "Sector 98, Noida", city: "Noida", state: "Uttar Pradesh", reraNumber: "UPRERAPRJ300532", projectStatus: "upcoming", possessionDate: "October 2030", startingPrice: 6, priceUnit: "Cr", propertyType: "residential", configurations: JSON.stringify(["3 BHK", "4 BHK", "5 BHK", "Penthouse"]), totalArea: "15 Acres", totalUnits: 350, images: JSON.stringify(["https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800", "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800"]), amenities: JSON.stringify(["Infinity Pool", "Private Gym", "Spa", "Concierge", "Private Theater", "Rooftop Garden"]), locationAdvantages: JSON.stringify([{ place: "Noida Expressway", distance: "2 min" }, { place: "DND Flyway", distance: "15 min" }]), floorPlans: JSON.stringify([]), featured: true, verified: true },
    { title: "Lodha The Park Worli", slug: "lodha-the-park-worli", description: "Sea-facing luxury in Worli with amenities by Trump Organization and Armani/Casa interiors.", highlights: JSON.stringify(["Sea-Facing in Worli", "Trump Organization Amenities", "Private Elevator", "Armani/Casa Interiors"]), builderName: "Lodha Group", location: "Worli, Mumbai", city: "Mumbai", state: "Maharashtra", reraNumber: "P51800001234", projectStatus: "ready-to-move", possessionDate: "Ready to Move", startingPrice: 8, priceUnit: "Cr", propertyType: "residential", configurations: JSON.stringify(["3 BHK", "4 BHK", "5 BHK", "Duplex Penthouse"]), totalArea: "17 Acres", totalUnits: 600, images: JSON.stringify(["https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800", "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800"]), amenities: JSON.stringify(["Infinity Pool", "Private Beach Club", "Spa", "Golf Simulator", "Tennis Court", "Concierge", "Valet Parking"]), locationAdvantages: JSON.stringify([{ place: "Sea Link", distance: "5 min" }, { place: "BKC", distance: "10 min" }, { place: "Airport", distance: "25 min" }]), floorPlans: JSON.stringify([]), featured: true, verified: true },
    { title: "BPTP Amstoria Plots Sector 102", slug: "bptp-amstoria-plots-sector-102", description: "Premium residential plots on Dwarka Expressway in gated community.", highlights: JSON.stringify(["Gated Community", "On Dwarka Expressway", "Well-Planned Infrastructure", "Near Diplomatic Enclave"]), builderName: "BPTP Limited", location: "Sector 102, Gurgaon", city: "Gurgaon", state: "Haryana", reraNumber: "RC/HARERA/GGM/2022/78", projectStatus: "ready-to-move", possessionDate: "Ready to Move", startingPrice: 2, priceUnit: "Cr", propertyType: "plots", configurations: JSON.stringify(["200 Sq Yd", "300 Sq Yd", "500 Sq Yd"]), totalArea: "200 Acres", totalUnits: 1200, images: JSON.stringify(["https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800", "https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800"]), amenities: JSON.stringify(["Gated Community", "Wide Roads", "Underground Electricity", "Parks", "24/7 Security"]), locationAdvantages: JSON.stringify([{ place: "Dwarka Expressway", distance: "On Expressway" }, { place: "IGI Airport", distance: "20 min" }]), floorPlans: JSON.stringify([]), featured: false, verified: true },
    { title: "Max Estate 128 Noida", slug: "max-estate-128-noida", description: "Grade A+ commercial towers with LEED Gold certification on Noida Expressway.", highlights: JSON.stringify(["Grade A+ Office Space", "LEED Gold Certified", "Smart Building Management", "Co-working Spaces"]), builderName: "Max Estates", location: "Sector 128, Noida", city: "Noida", state: "Uttar Pradesh", reraNumber: "UPRERAPRJ671234", projectStatus: "under-construction", possessionDate: "December 2026", startingPrice: 1.2, priceUnit: "Cr", propertyType: "commercial", configurations: JSON.stringify(["Office Suites", "Co-working", "Retail"]), totalArea: "8 Acres", totalUnits: 200, images: JSON.stringify(["https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800", "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800"]), amenities: JSON.stringify(["Central AC", "High-Speed Elevators", "Food Court", "Business Lounge", "EV Charging"]), locationAdvantages: JSON.stringify([{ place: "Noida Expressway", distance: "On Expressway" }, { place: "Sector 137 Metro", distance: "8 min" }]), floorPlans: JSON.stringify([]), featured: false, verified: true },
  ];

  for (const project of projects) {
    await prisma.project.create({ data: project });
  }
  console.log(`  Created ${projects.length} projects.\n`);

  // ===================== SITE SETTINGS =====================
  console.log("Setting up site settings...");
  await prisma.siteSettings.upsert({
    where: { id: "default" },
    create: { id: "default" },
    update: {},
  });
  console.log("  Done.\n");

  console.log("=== Seed Complete ===");
  console.log("\nLogin credentials:");
  console.log("  Admin: admin@propertypointers.com / admin123");
  console.log("  User:  user@propertypointers.com / user123");
}

main()
  .catch((e) => {
    console.error("Seed error:", e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
